package com.kikiBettingWebBack.KikiWebSite.entities;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Represents a booking code generated by an admin.
 * Contains a pre-built slip (games + picks) that users can load
 * by entering the code. Multiple users can place bets against the same
 * booking code — each placement creates its own PlacedBet record.
 *
 * Example code format: AXKP-7BM2
 */
@Entity
@Table(name = "booking_codes")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BookingCode {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The short human-readable code shown to admin + shared with users.
     * Format: XXXX-XXXX (uppercase alphanumeric, 8 chars + dash).
     */
    @Column(name = "code", nullable = false, unique = true, length = 10)
    private String code;

    /**
     * Pre-calculated product of all game odds on this slip.
     * Stored so users see it immediately without recalculating.
     */
    @Column(name = "combined_odds", nullable = false, precision = 10, scale = 4)
    private BigDecimal combinedOdds;

    /**
     * Total number of games on this slip (1–10).
     */
    @Column(name = "game_count", nullable = false)
    private int gameCount;

    /**
     * Whether admin included score predictions on this slip.
     */
    @Column(name = "includes_score_prediction", nullable = false)
    @Builder.Default
    private boolean includesScorePrediction = false;

    /**
     * Booking codes can be deactivated by admin so no new bets can be placed.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private BookingCodeStatus status = BookingCodeStatus.ACTIVE;

    /**
     * The admin user who generated this code.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    private User createdBy;

    /**
     * All games + pre-set picks that make up this booking slip.
     */
    @OneToMany(mappedBy = "bookingCode", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @Builder.Default
    private List<BookingCodeGame> games = new ArrayList<>();

    /**
     * All bets users have placed using this booking code.
     */
    @OneToMany(mappedBy = "bookingCode", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<PlacedBet> placedBets = new ArrayList<>();

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Optional expiry — null means no expiry.
     */
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    public boolean isExpired() {
        return expiresAt != null && LocalDateTime.now().isAfter(expiresAt);
    }

    public boolean isUsable() {
        return status == BookingCodeStatus.ACTIVE && !isExpired();
    }
}